# -*- coding: utf-8 -*-
"""Assignment3ITC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jadKe-I_8AljxjjfUsYOvj8JBKRycKT-
"""

import sys
from scapy.all import *
from socket import *


#Enter four parameters into the commandline 1-filename 2-target IP 3-min port 4-maxport
#check if all four parameters are specified 
if len(sys.argv) !=4: 
    body += "Usage: %s target startport endport"%(sys.argv[0])
    sys.exit(0)


#assign inputs to variable names
target = str(sys.argv[1])
startport = int(sys.argv[2])
endport = int(sys.argv[3])

body = 'scanning '+ target +' for open ports\n'
body += "<br />"
body += "<br />"

#ICMP Scan
ans,unans=sr(IP(dst=target)/ICMP())
body += target + " is alive"
body += "<br />"

#if we are scanning one port, increment the endpoint by one
if startport == endport:
    endport+=1

body += "<br />"
body += "TCP, UDP, and Traceroute scanner"
body += "<br />"

#Loop through ports specified
for portNumber in range(startport, endport):  
  #TCP port scan
  packet = IP(dst=target)/TCP(dport=portNumber,flags='S')
  response = sr1(packet, timeout=.5,verbose=0)
  if response.haslayer(TCP) and response.getlayer(TCP).flags==0x12:
    body += 'port '+str(portNumber)+' is open - TCP'
    body += "<br />"
  sr(IP(dst=target)/TCP(dport=response.sport, flags='R'),timeout=0.5,verbose=0)

  #UDP port scan
  pkt = IP(dst=target)/UDP(dport=portNumber)
  udpResponse = sr1(pkt, timeout =.5, verbose=0)
  if udpResponse == None:
    body += '/n port '+str(portNumber)+' is open - UDP'
    body += "<br />"

  #Traceroute scan
  pkt2 = IP(dst=target, ttl=portNumber) / UDP(dport=33434)
  reply = sr1(pkt2, verbose=0)
  if reply is None:
      break
  elif reply.type == 3:
      body += "Done! " + reply.src
      body += "<br />"
      break
  else:
      body += "%d hops away: " % portNumber, reply.src, reply.time
      body += "<br />"

body += "<br />"
body += 'scan is complete!'

#Create html page
output = "<html><body><p>"
output += body
output +="</p></body></html>"'"'
file = open("BrittanyPortScanner.html","w")
file.write(output)
file.close()



